### ISSUE TITLE
🐞 bug : 알람 찾기에서 알람이 추가가 안되는 현상

### ISSUE THREAD

**Issue by tea-hkim** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#83]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 | 관련 이슈 |
|:---:|:---:|:---:|:---:|
| 220813 | 알람 찾기 뷰 | 알람 찾기가 안됨 |  |

## 증상 

1. 알람 찾기 뷰에서 알람 찾기 버튼을 눌렀을 때 어떠한 애니메이션도 없습니다.
2. 알람 추가를 누른 결과 Alert 창이 나오지 않고 알람이 추가 되지 않는 현상이 있습니다.
## 스크린샷

![Simulator Screen Recording - iPhone 13 - 2022-08-13 at 13 59 50](https://user-images.githubusercontent.com/81206228/184469228-3b890c55-ce9d-4bb8-ac03-f20475157b1b.gif)

**Comment by chaneeii** [comment]
제가 해결해보겠습니다!
